os: osx
osx_image: xcode10.3
language: objective-c
script:
  - set -o pipefail && xcodebuild -workspace "Horoscopo.xcworkspace" -scheme "Horoscopo" -destination "platform=iOS Simulator,OS=12.4,name=iPhone Xs Max" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty

branches:
 only:
 - master
